version: '3.8'

services:
  web:
    build: . 
    command: uvicorn main.asgi:application --host 0.0.0.0
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: